inputs:
- alias: "ccda_response_files"
  properties:
    type: "dataset"
    dataset:
      rid: "ri.foundry.main.dataset.8c8ff8f9-d429-4396-baed-a3de9c945f49"
      assumedMarkings: []
outputs:
- alias: "dq_ccda_snooper_people"
  properties:
    type: "dataset"
    dataset:
      rid: "ri.foundry.main.dataset.8cb5366c-e7e2-46ef-af2f-a485269a1a01"
runtime:
  type: "managedContainer"
  managedContainer:
    identifier: "code-workspaces-jupyter-python-3_9-image"
    command: "/opt/palantir/transforms.d/run-ipynb.sh"
    filePath: "DQ_ccda_snooper_people.ipynb"
    envVars:
      ENABLE_CODE_BUDDY: "false"
      ENABLE_MANAGED_CONDA_ENVIRONMENTS: "true"
      ENABLE_MANAGED_CRAN_ENVIRONMENTS: "false"
      ENABLE_MANAGED_R_CONDA_ENVIRONMENTS: "false"
      ENABLE_WRITE_BRANCH_PREFIX: "false"
      UPLOAD_CODE_CHECKPOINTS: "true"
resources:
  cpu: "1"
  memory: "8G"
shouldArchiveLogsToOutputs: false
