#!/usr/bin/env python3

"""
 count_vocab_by_section.py
 This script produces code, codeSystem pairs and counts with the section element_id they came from
 to aid in analysis related to producing the vacabulary maps.

 INPUT: ccda_coverage_snooper.csv generated by ccda_coverage_snooper.py
        section_oid.csv, vocab_oid.csv
 OUTPUT: count_vocab_by_section.csv

"""

import pandas as pd


def main():

    vocab_oid_df = pd.read_csv("vocab_oid.csv")
    vocab_oid_df = vocab_oid_df.rename(columns={"oid": "codeSystem"})

    section_oid_df = pd.read_csv("section_oid.csv")
    section_oid_df = section_oid_df.rename(columns={"oid": "template_id"})

    raw_df =  pd.read_csv("ccda_coverage_snooper.csv")
    df = raw_df.merge(section_oid_df, on=["template_id"], how="left")
    df = df.merge(vocab_oid_df, on=["codeSystem"], how="left")

    # ,filename,template_id,path,field_tag,attributes,code,codeSystem,name,priority
    #counts_df = df.groupby(['code', 'codeSystem', 'name']).size().reset_index(name='counts')
    counts_df = df.groupby(['code', 'vocabulary_id', 'name']).size().reset_index(name='counts')
    counts_df.sort_values(by="counts", ascending=True, inplace=True, kind='mergesort')
    counts_df = counts_df.rename(columns={"name": "section_name"})

    counts_df.to_csv("/foundry/outputs/count_vocab_by_section.csv")

    if True:
        from foundry.transforms import Dataset
        count_vocab_by_section = Dataset.get("count_vocab_by_section")
        count_vocab_by_section.write_table(counts_df)


if __name__ == "__main__":
    main()

